### ISSUE TITLE
Click to the task will reoder its

### ISSUE THREAD

**Issue by alexprey** [mantisbt-plugins/Taskodrome#1]
When I click to task on the "Assigned board" then task will reordered in the list

**Step for reproduce:**

1. Create a two tasks and assigned it for one person
2. Open a "Assigned board"
3. Click to first task in the list

**Expected:**
Task still position in the list

**Actual:**
Task move to second position

**Comment by AuthenticEshkinKot** [comment]
Fixed in #8
