### ISSUE TITLE
Work for Subprojects and not for Project

### ISSUE THREAD

**Issue by ducemmanuel** [mantisbt-plugins/Taskodrome#10]
Hello

When I open the Taskodrome view for a subproject I see all issues, but if I'm on the project level no informations are open.
It should be interesting to have a consolidate view of all issues on the project level.

Best regards.
Emmanuel

**Comment by AuthenticEshkinKot** [comment]
@ducemmanuel
I've tried to reproduce it and unfortunately, got nothing interesting. My steps:

1. I've created project "First", its subproject "First_sub1 and its subproject "First_sub1_sub1". Now my project list looks like:
First
  >> First_sub1
    >> >> First_sub1_sub1
2. I've added some issues to "First", some other issues to "First_sub1" and a couple of issues to "First_sub1_sub1"
3. Issues, that were added to "First_sub1_sub1", can be found in "First" project and in both subprojects of this hierarchy.
4. Issues of "First_sub1" can be found in this subproject and in "First" project.
5. Issues of "First" belong only to "First".

As far as I know, this is correct behavior. Could you describe how to reproduce your bug?
