### ISSUE TITLE
Add possibility to filter taskodrome by "Product version"

### ISSUE THREAD

**Issue by mmpetrova** [mantisbt-plugins/Taskodrome#106]

**Comment by alexprey** [comment]
It's great idea, but I think it's provide the more usability if its will be is not a filter, but its will be a grouping  in table with tasks.

For example its can looks like in Jira Ajile plugin when used the swimlines for User stories.
I try to draw the simple sketch how it's can looks:
![image](https://cloud.githubusercontent.com/assets/7888563/25063320/ea9c7492-21e9-11e7-91e2-af577e019c3f.png)

----------------
.Regars Alexey,
sdCloud.io dev team.

**Comment by AuthenticEshkinKot** [comment]
@alexprey @mmpetrova 
I've added this possibility. Please, check it out.

**Comment by ivan-perl** [comment]
Works fine. I guess this case can be closed.

Regards,
Ivan
sdCloud.io team
