### ISSUE TITLE
Description field not escaped before emitting into html

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/Taskodrome#111]
The summary field is escaped but not the description.  See main.php on mantisbt_2.0.0.  I haven't checked other branches.

**Comment by AuthenticEshkinKot** [comment]
@vboctor 
I'm not sure that I've understood right, but from now all HTML-tags will be filtered out from description and summary, because tags can't be applied by EaselJS.

**Comment by vboctor** [comment]
Sounds good.    Looks like you escaped description field as part of https://github.com/mantisbt-plugins/Taskodrome/pull/126/files

**Comment by AuthenticEshkinKot** [comment]
OK, closing issue
