### ISSUE TITLE
Only first page of issues are visible on the board

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/Taskodrome#112]
Should all issues that match current filter be visible with potentially an upper limit, e.g. 500 issues.  One page of issues seems to be a small number.

**Comment by alexprey** [comment]
@AuthenticEshkinKot do you have any news about this bug? It's really block the work with board :(

----
From sdCloud.io team with love <3

**Comment by AuthenticEshkinKot** [comment]
@vboctor @alexprey 
Please, check it out.
