### ISSUE TITLE
Add issues count in columns

### ISSUE THREAD

**Issue by ivan-perl** [mantisbt-plugins/Taskodrome#127]
On status an assign boards it will be nice to have a total number of issues per column. For assignment and status board total issues count can be placed in a column header like this:
![image](https://cloud.githubusercontent.com/assets/9080607/25771901/8f612752-3266-11e7-8fe1-32cc1ad5e2c1.png)
Same for status board.

As an addition it will be great to have per-version metrics in the header of each release like this:
![image](https://cloud.githubusercontent.com/assets/9080607/25771931/20c17df0-3267-11e7-91c4-af1ca42d0ea0.png)

Regards,
Ivan
sdCloud.io team

**Comment by AuthenticEshkinKot** [comment]
@ivan-perl 
Done. Please, check it out.
