### ISSUE TITLE
Difficulty reading text when using markdown

### ISSUE THREAD

**Issue by didaquis** [mantisbt-plugins/Taskodrome#132]
Difficulty reading text when using markdown (see the image). HTML tags are so confusing for users.

![markdown](https://cloud.githubusercontent.com/assets/6883041/25951927/7c857064-365f-11e7-90d3-afb6d02a90ac.JPG)

**Comment by AuthenticEshkinKot** [comment]
@didaquis 
I've fixed this issue some commits ago, in 90c1b947d1ba39a057d6a0fc36be232b85fdb476. Are you sure that you're using the latest version?

**Comment by didaquis** [comment]
> Are you sure that you're using the latest version? 

Probably not! Thank you for your help.
