### ISSUE TITLE
Horizontal scrollbar placed at bottom of page and hidden on small screen

### ISSUE THREAD

**Issue by alexprey** [mantisbt-plugins/Taskodrome#137]
When task list is very huge and project has many columns for statuses or many users then we have two scrollbars, but horizontal scrollbar visible only when vertical scrollbar scrolled to bottom.

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
In Taskodrome 1.0 I've added an ability to scroll it with arrow keys. Also, it should be scrolled automatically when you bring a card to an edge of the screen.

**Comment by alexprey** [comment]
I test the card move to the edge and it's not work for me.
Scrolling with arrows its a workaround, it's a not fix this bug, because many users prefer scrolling with mouse it more quickly and easy.

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
But for me it works correctly both on Linux/FF and Win/Chrome. Maybe it's related to your browser cache.

**Comment by alexprey** [comment]
Ok, I test again, now draggin the issue-card is scroll the area.

**Comment by alexprey** [comment]
But problem with scrolling by default way via horizontal scrollbar is still stay :(
