### ISSUE TITLE
Status workflow is not taken into account

### ISSUE THREAD

**Issue by TomR** [mantisbt-plugins/Taskodrome#14]
It seems dat the status workflow defined is not into taken account. I can move any issue to any status but my status workflow should not permits this.

**Comment by AuthenticEshkinKot** [comment]
@TomR 
I've reproduced this bug and I've found, that it appears even when using default UI. Does it appears when you are using default UI?

**Comment by TomR** [comment]
I am using MantisBT 1.2.19 with default UI. ( no changes whatsoever )

**Comment by AuthenticEshkinKot** [comment]
@TomR 
I have same version.
Could you reproduce this bug using only default mantisbt interface - "View issues" -> select issue by ID -> "Change status to:"?

**Comment by TomR** [comment]
In MantisBT in default U only the statusses are shown in the dropdown at the top as wel as the dropdown in de issue details which are in the workflow.
So when a issue is status "Resolved' my workflow is only permitting status to be changed to Closed or Reopened ( = custom status ). However when I use your plugin I am able to move the issue around to any status,  which is not correct.

Have a take a look at: http://www.mantisbt.org/bugs/view.php?id=14496

Do you have setup your workflow correctly?

**Comment by AuthenticEshkinKot** [comment]
@TomR 
I've explored these problem deeper and found some mistakes in my test environment. So, everything is OK with mantisbt - it's bug of Taskodrome :)

**Comment by TomR** [comment]
OK, will wait for a solution.

**Comment by AuthenticEshkinKot** [comment]
@TomR 
Fix is ready, I will wait for your feedback.
