### ISSUE TITLE
Add shadow to the card which in drag-mode.

### ISSUE THREAD

**Issue by alexprey** [mantisbt-plugins/Taskodrome#150]
Add shadow to the card which in drag-mode.

![image](https://user-images.githubusercontent.com/7888563/27014016-32f85a54-4ef8-11e7-86e5-e88af8892471.png)

---
From sdCloud.io tead with love <3

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
It's ready, check it out

**Comment by alexprey** [comment]
@AuthenticEshkinKot 
All issues now looks strange and no shadow yet while dragging card
![image](https://user-images.githubusercontent.com/7888563/27800711-41c9b87a-6023-11e7-907f-cae58ca1472e.png)

**Comment by alexprey** [comment]
Just for example looks in Jira:
![image](https://user-images.githubusercontent.com/7888563/27800762-6fba2ce2-6023-11e7-8fce-48c4db3e84f8.png)

or in Trello:
![image](https://user-images.githubusercontent.com/7888563/27800792-89fc3ece-6023-11e7-8b2b-7eca1b0bfa13.png)

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
![shadow](https://user-images.githubusercontent.com/2103955/27803040-246dbb8e-6030-11e7-8f45-38bf2766f62d.png)
Is it a shadow, isn't it?|

**Comment by alexprey** [comment]
@AuthenticEshkinKot Yes, it's look more understandable. I hope that shadow render only for cards that is drag at the current moment

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
Yes, it's so
