### ISSUE TITLE
Port LOST for details

### ISSUE THREAD

**Issue by jcarlosrga** [mantisbt-plugins/Taskodrome#158]
If you have MANTIS in a port, different to 80, it's lost when try to see the details of an issue.

**Comment by AuthenticEshkinKot** [comment]
@jcarlosrga 
Are you sure, that it is related to the plugin?

**Comment by aspavlov** [comment]
it is a plugin related bug. You try to generate full url here: 

function getPathToMantisFile(window, filename) {
  var protocol = window.location.protocol;
  var hostname = window.location.hostname;

  var path = window.location.pathname.substr(0, window.location.pathname.lastIndexOf("/"));

  var result = protocol + "//" + hostname + path + "/" + filename;

  return result;
};

There is no port info... hostname does not have port inside...

**Comment by AuthenticEshkinKot** [comment]
@aspavlov 
Попробуйте заменить hostname в этом скрипте на host.

**Comment by aspavlov** [comment]
@AuthenticEshkinKot 

вот фикс, который работает: 

function getPathToMantisFile(window, filename) {
  var protocol = window.location.protocol;
  var hostname = window.location.hostname + ":" + window.location.port;

  var path = window.location.pathname.substr(0, window.location.pathname.lastIndexOf("/"));

  var result = protocol + "//" + hostname + path + "/" + filename;

  return result;
};
