### ISSUE TITLE
The yellow color of issue-card date is very hard to reading

### ISSUE THREAD

**Issue by alexprey** [mantisbt-plugins/Taskodrome#159]
Please use more user-friendly color for it.

![image](https://user-images.githubusercontent.com/7888563/27223416-ffeeb672-5298-11e7-84bb-45d72bfc107d.png)

-----
From sdCloud.io team :)

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
I've made some changes in color scheme https://github.com/mantisbt-plugins/Taskodrome/commit/eb8b8388878ed0c70d31def87d0a7664cfd9903f. Please, check it out and give a feedback.

**Comment by alexprey** [comment]
I think that using an auto-generated colors is not a good idea. Autogenerated colors looks good when color changed in liner time in short realtime period, when user have continues contact with this text item. 
Specify for design some pallet of required colors that looks are good. For example it maybe 5 or 6 primary colors. Or may be think about another way to figure out this information, may be as in Jira use dots - that indicate count of days when this task is not updated.

**Comment by alexprey** [comment]
Great! Thanks, now it's looks very usefully and gracefully! 👍
