### ISSUE TITLE
The column width is not adjusted after window resizing

### ISSUE THREAD

**Issue by alexprey** [mantisbt-plugins/Taskodrome#164]
The column width is not adjusted after window resizing

![image](https://user-images.githubusercontent.com/7888563/27290425-e00630e0-5515-11e7-94ea-ea382f44307b.png)

----------------
From sdCloud.io with love <3

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
Is it resizing after F5?

**Comment by alexprey** [comment]
Yep
