### ISSUE TITLE
Grouping by version works incorrect

### ISSUE THREAD

**Issue by alexprey** [mantisbt-plugins/Taskodrome#166]
See this issue https://github.com/mantisbt-plugins/Taskodrome/issues/165

In group of version shown issues from "Product version", for grouping should use the "Target version" field.
See logic of "Roadmap" page in mantis, it use the correct grouping.

-------------
From sdCloud.io team with love <3

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
Fixed, check it out.

**Comment by alexprey** [comment]
Thanks, now it work fine :)
