### ISSUE TITLE
Task without version is not showned on assigned board

### ISSUE THREAD

**Issue by alexprey** [mantisbt-plugins/Taskodrome#175]
Issues that doesn't have version is not displaying on assigned board, but on status board is ok.

------
From sdCloud.io team with love <3

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
Unfortunately, I can't reproduce this bug.

**Comment by alexprey** [comment]
Oh... yes, it's related with scrolling bug... Because it hard to understand that I can scroll board by horizontal axis.
You can close this issue.
