### ISSUE TITLE
Clarify branches in readme

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/Taskodrome#181]
As per other plugins, it is recommended to be explicit about supported MantisBT versions in readme file and indicate which branch is used for which release versions.

For example, it is unclear whether users should use `master` or `mantisbt-2.0.0` for MantisBT 2.x releases.

Here is an example of another plugin:
https://github.com/mantisbt-plugins/source-integration

**Comment by AuthenticEshkinKot** [comment]
@vboctor 
Done
