### ISSUE TITLE
Reflect an active board in URL

### ISSUE THREAD

**Issue by alexprey** [mantisbt-plugins/Taskodrome#182]
It's a good idea to store information about active board in URL.
You can use this feature of the browser to change state of URL: 
https://developer.mozilla.org/en/docs/Web/API/History_API

Those add the next cool features to Taskodrom:

1. After page reloading user stay on the same board
2. User can use "Back" and "Forward" buttons to navigate between boards

What do you think about this improvement?

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
For now, user already stays on last active board after page reload. The last active board is a board, where user made the last change. But maybe you're right and it would be better if the last active board would be the last _viewed_, regardless of changes.
As I understand it, History API gives an ability to navigate browser's history. But transferring from one board to another doesn't require full page reload - it's just a change of board's style parameters. So, it's not visible for browser history mechanism.

**Comment by alexprey** [comment]
@AuthenticEshkinKot 
> But maybe you're right and it would be better if the last active board would be the last viewed, regardless of changes.
Yes, it's more understandable and user friendly flow.
> As I understand it, History API gives an ability to navigate browser's history. But transferring from one board to another doesn't require full page reload
History API gives method to change URL and store some additional information and also you can subscribe on method that invoked when user navigate by "Forward" and "Next" buttons, and you can read stored information. 
See `history.pushState` and `window.onpopstate`.

**Comment by AuthenticEshkinKot** [comment]
@alexprey 
From now on the last viewed board will be kept after page refresh.

**Comment by alexprey** [comment]
Great, thanks :)
