### ISSUE TITLE
Introduce black lists for users and statuses on boards

### ISSUE THREAD

**Issue by ivan-perl** [mantisbt-plugins/Taskodrome#195]
As a user, I don't to see all project users and statuses on the board. Some users may represent 3pp integrations and system accounts. Some statuses maybe used as issues vaults.

Please, introduce two new plugin settings: List of hidden users and list of hidden statuses. Value for both of them can be a comma separated strings. Default values are empty lists.

-------------------
With Best Whishes,
Friends from sdCloud.io

**Comment by AuthenticEshkinKot** [comment]
@ivan-perl 
I've added blacklist, check it out, please
