### ISSUE TITLE
Change Language Settings causes blank "Status Board"

### ISSUE THREAD

**Issue by toms1342** [mantisbt-plugins/Taskodrome#208]
Thank you for this wunderful plugin. It works like a charm...in english :)
 
If a user change the language in his MantisBT preferences, actual changed from english to german, 
the "Status board" keeps blank. The "Assignment Board" is working properly. 
I tested other languages with the same effect. "Assingment Board" working, "StatusBoard" blank. 
Any idea, what possibly is wrong?

MantisBT 2.5.1
PHP 7.0.22-0ubuntu0.16.04.1
Schema Version 209
ADOdb Version 5.20.9

**Comment by AuthenticEshkinKot** [comment]
Hi, @toms1342 
I've tried to reproduce your bug on fresh installation of Mantis 2.6.0. I've copied "strings_english.txt" to "strings_german.txt" and changed variable, that is responsible for Status Board, and switched language in mantis. And now I see that everything is OK.
Please, try to do the same and check the result. Also, it may be useful to check all quotation marks.

**Comment by toms1342** [comment]
Thank you for your fast response. It is not a bug! It is more something like a workaround that has to be done. Here is what I did:
My goal was to hide the user "administrator".
So I put his name on the list of "Hidden users" and did "Update Konfiguration". 
![image](https://user-images.githubusercontent.com/29711367/30888190-6d3d35e2-a31f-11e7-9771-e870517f76d3.png)
The following was written to the MantisBT config:
![image](https://user-images.githubusercontent.com/29711367/30888204-808f2cfe-a31f-11e7-903a-73c911492248.png)
This was the problem. 
For the future I will take care to check, if there are any entries in the MantisBT configuration, that prevent  
the pluging from working properly.

**Comment by toms1342** [comment]
Do you plan to integrate a rigths management? 
It would be very helpful to define who can use the plugin (user threshold).
For example:
Viewers, Reporters and Testers have no access ... Developers, Managers can access the plugin.

**Comment by AuthenticEshkinKot** [comment]
@toms1342 
If you want to apply configuration to specific project, you should choose this project in dropdown list in upper right corner. It's mantis's element and it's always there.
You can manage rights in mantis itself. Take a look at pages at "Manage->Manage Configuration".
