### ISSUE TITLE
Issue assignment visibility overridden.

### ISSUE THREAD

**Issue by tezma90** [mantisbt-plugins/Taskodrome#210]
I have set reporter level users to not be able to see the person an issue is assigned to and also to only be able to see their own issues. 
Using taskodrome reporter level users have access to the plugin, and they see which user their issue is assigned to completely disregarding mantis configuration.

**Comment by AuthenticEshkinKot** [comment]
@tezma90 
How did you achieve this? Did you make all issues private?

**Comment by tezma90** [comment]
Under Manage > Manage Configuraition > Workflow Threshold > Issues > Limit reporter's access to their own issues set to true.
 Manage > Manage Configuraition > Workflow Threshold > Other > View Assigned To set to false.

**Comment by AuthenticEshkinKot** [comment]
@tezma90 
I've applied your settings to every MantisBT version, supported by the plugin (in my case - 1.2.9, 1.3.0 and 2.0.0), and I should say, that reporter sees issues created by himself and nothing more. And this behaviour is same for the tracker and the plugin.
What version of MantisBT do you use?

**Comment by tezma90** [comment]
I was using version 2.8.0
Then I guess it's simply that, my bad.

**Comment by AuthenticEshkinKot** [comment]
@tezma90 
I've tried to reproduce it in MantisBT 2.8.0 and got same visibility both in the plugin and in the tracker.

**Comment by tezma90** [comment]
@AuthenticEshkinKot yes, I can not reproduce the problem anymore.
