### ISSUE TITLE
Taskodrom dosn't display information about relationships of issues

### ISSUE THREAD

**Issue by alexprey** [mantisbt-plugins/Taskodrome#212]
We have some couple of issues. One of those it is an Epic issue, and other related to this as child. F.ex.

issue.001 - Epic
issue.002 - Some implementation for Epic (Child of issue.001)
issue.003 - Some another implementation for Epic (Child of issue.001)
issue.004 - Some addtional changes for Epic (Child of issue.001)
issue.005 - Issue for testing of Epic (Child of issue.001)
issue.006 - Some related bug that found in testing of Epic tasks (Child of issue.001)

![image](https://user-images.githubusercontent.com/7888563/32656527-35bda6f2-c623-11e7-9ed7-a87754098cd8.png)

Simple sketch:

![image](https://user-images.githubusercontent.com/7888563/32658583-b5c3eeee-c62b-11e7-8369-682e6e472a28.png)

And plugin shown it in different places and it hard to understand which tasks is related with another.
It would be great to shown this issues by different way, may be it should be the separate swimline for Epic issue and all child issue should be placed into it swimline, like an in Jira agile board.

For detecting the correct tree structure, require to see relationships for "parent of" and "child of".

Also it would be good, if we should all relation ships in tooltip dialog.

-------------------
Regrads,
Alexey from [sdCloud.io](http://sdcloud.io) development team with love <3

**Comment by Amizcho** [comment]
If the relationship of issues can be shown in here 
may a great help to monitor issues status.

**Comment by AuthenticEshkinKot** [comment]
@alexprey, @Amizcho 
I remember this issue and it is still under construction =)

**Comment by AuthenticEshkinKot** [comment]
@alexprey, @Amizcho 
Feel free to check out the latest version
