### ISSUE TITLE
Cannot install_ because not presented on Manage Plugins

### ISSUE THREAD

**Issue by Amizcho** [mantisbt-plugins/Taskodrome#218]
Hi,

1. download this plugin for mantisbt_2.0.0 
2. save this plugin to mantisbt/plugin
3. login mantis to install it , but there is no this plugin on Manage Plugins

Mantis version is 2.5.1.
PHP is 7.1.6.
Could you give me some advice?

![1 save it on plugins folder](https://user-images.githubusercontent.com/34676390/34514614-28ce4c48-f0a9-11e7-8dbd-8b59a6764442.JPG)
![2 no presented on manage plugins](https://user-images.githubusercontent.com/34676390/34514616-29152c6c-f0a9-11e7-8f40-673216ef4bb5.JPG)

**Comment by AuthenticEshkinKot** [comment]
Hi @Amizcho 
This Taskodrome folder must contain Taskodrome.php, files, lang, etc. and must not contain Changelog.md, Screenshots, etc. In other words, it should not be from the repo root, but from Taskodrome folder.

**Comment by Amizcho** [comment]
![path](https://user-images.githubusercontent.com/34676390/34596432-a083fbe4-f21a-11e7-9d05-4e04f5e50c6e.JPG)
Thanks very much. It works now. 
I deleted the Screenshots folder and other files, and it became OK.
