### ISSUE TITLE
403 Forbidden on scripts/*.js

### ISSUE THREAD

**Issue by lbayle** [mantisbt-plugins/Taskodrome#24]
Hi,
I am using Mantis 1.3.0_RC1 (no, I can't rollback to 1.2, there are features in 1.3 I realy need), and I have trouble with your plugin.
Mabe this has nothing to do with it, but I have many 403 errors :

best regards.

"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/grid_common_utils.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/easeljs-0.8.2.min.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/devs_grid.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/on_load_opening.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/grid_draw_utils.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/status_grid.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/grid_common_utils.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/grid_draw_utils.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/devs_grid.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/status_grid.js"
"NetworkError: 403 Forbidden - http://localhost/mantis13/plugins/Taskodrome/scripts/on_load_opening.js"

**Comment by AuthenticEshkinKot** [comment]
@lbayle 
I've got special Taskodrome edition for mantisbt 1.3.0_rc.1, you can find it here - https://github.com/AuthenticEshkinKot/Taskodrome/tree/mantisbt_1.3.0_rc.1.
Anyway, this error doesn't look like a bug of Taskodrome. Maybe there is something wrong with server settings or file system permissions?

**Comment by lbayle** [comment]
Hi,
thank you for your quick answer.
I am trying this on Windows/XAMPP which is for me an odd platform where I'm
not familiar with permissions.
Tomorow I'll test it on a Linux server, with hopefully more success !


best regards
Louis

Louis BAYLE
Tel: +33 (0)4.42.604.734
lbayle.work@gmail.com

**Comment by AuthenticEshkinKot** [comment]
@lbayle 
Hi,
I suppose, that I've found a solution for this problem:

1. Get the most recent version of Taskodrome from mantisbt_1.3.0_rc.1 branch 
2. Add the following line to your Apache's httpd.conf (if it is not already there): 
LoadModule access_compat_module modules/mod_access_compat.so
