### ISSUE TITLE
Support for version 2.18.0

### ISSUE THREAD

**Issue by cedrickzepp** [mantisbt-plugins/Taskodrome#274]
Support for version 2.18.0
I installed the file Taskodrome-mantisbt_2.0.0 but, regrettably, it is not compatible with version 2.18.0, help, please!

Best regards...

**Comment by AuthenticEshkinKot** [comment]
@cedrickzepp 
Hello!
Could you provide more detailed description? I've installed mantisbt 2.19.0 and taskodrome works with no problem.

**Comment by cedrickzepp** [comment]
I did the installation using GIT and it does not appear in the list of plugins: attached screenshots ...
![screenshot 2019-02-26 at 13 28 40](https://user-images.githubusercontent.com/47735589/53440683-c1da5880-39ca-11e9-80d5-4212959f6b02.png)
![screenshot 2019-02-26 at 13 28 19](https://user-images.githubusercontent.com/47735589/53440684-c1da5880-39ca-11e9-9cfb-31a6c23bce52.png)
![screenshot 2019-02-26 at 13 28 06](https://user-images.githubusercontent.com/47735589/53440685-c272ef00-39ca-11e9-8c2f-b5fcda0a5704.png)

**Comment by AuthenticEshkinKot** [comment]
@cedrickzepp 
I think that you need to add Taskodrome/Taskodrome directory to "plugins", not Taskodrome/ itself. To check the correctness of your installatioin, just execute "ls Taskodrome" - if "files" directory is there, then everything should be OK.

**Comment by cedrickzepp** [comment]
Success, exactly so install it and it works perfect.
