### ISSUE TITLE
Status Board don't show issues

### ISSUE THREAD

**Issue by MWNemesis** [mantisbt-plugins/Taskodrome#294]
I'm the administrator of the project and i need to have a tool to monitor the status of any issue of a specific project, actually the Tskodrome seams to show only the issue assigned to me, there is a way to schive that goal?

**Comment by AuthenticEshkinKot** [comment]
Hello, @MWNemesis !
Does Status board show all issues that are shown on Assignment board?

**Comment by MWNemesis** [comment]
> Hello, @MWNemesis !
> Does Status board show all issues that are shown on Assignment board?

Actually I see all the issues correctly assigned to the users in the Assign board but in the status board I have 0 issues

**Comment by AuthenticEshkinKot** [comment]
I know this bug and I'll try to fix it in next few days.

**Comment by AuthenticEshkinKot** [comment]
@MWNemesis 
It should be OK now, feel free to check it out
