### ISSUE TITLE
Default sort in plugin

### ISSUE THREAD

**Issue by orokhovatskiy** [mantisbt-plugins/Taskodrome#305]
Hello, thank you for great plugin.

I have two mantisbt systems with different versions of Taskodrome:
1.4.7 - sort works perfectly and copy settings from "view issues". In this view I have filter with sort by 'priority DESC' then by 'date created ASC';
2.1.5 - it doesn't take into account filter from "view issue". It sorts by date created ASC and don't care priority and applied filters.

Can I fix it or hardcode the sort?

**Comment by JeremyOWO** [comment]
Hello, 

I encountered exactly the same problem, so I provide a pull request to take into account original filter sortinghttps://github.com/mantisbt-plugins/Taskodrome/pull/315
