### ISSUE TITLE
To long textstring in summary text does not fit in an issue card

### ISSUE THREAD

**Issue by JaapJ** [mantisbt-plugins/Taskodrome#45]
When we add a to long text string into the summary field then this text would not fit in the issue-card in the Taskodrome boards. Fixing this issue would be a nice tweak! Detected this due to the fact that other people might have the habit to cut and past error messages direct into the summary / description field.

Steps to reproduce:
Report a bug with the following summary text:
Card test TO_LONG_WORD_IN_SUMMARY_TEXT_FIELD
(see 1)

After Updating the information
We see at Taskodrome that this text does not fit into the issue-card.
(see 2)

![1](https://cloud.githubusercontent.com/assets/22151164/18550309/76835450-7b53-11e6-9dde-d0bd2acfd4fb.png)

![2](https://cloud.githubusercontent.com/assets/22151164/18550326/875b965c-7b53-11e6-9d67-499ac9fa0092.png)

**Comment by AuthenticEshkinKot** [comment]
Solved in v1.0
