### ISSUE TITLE
Update UI to the new mantisbt 2.0 GUI style

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/Taskodrome#92]
Current implementation of Taskodrome looks like this on 2.0:
![image](https://cloud.githubusercontent.com/assets/4140247/22618021/5b5931a6-eaa0-11e6-8ac3-e8c580949fe4.png)
The styles clashe. Any plans to tweak this?

**Comment by AuthenticEshkinKot** [comment]
I have a desire to change it, but haven't got any mockups.
