### ISSUE TITLE
Project name in grid

### ISSUE THREAD

**Issue by b4rt3kpl** [mantisbt-plugins/Taskodrome#96]
Is it possible to add project name in grid additional to issue subject in assigment board and status board?

**Comment by AuthenticEshkinKot** [comment]
@b4rt3kpl 
Hello!
There is no such functionality for today, but I'm sure, that it can be added.

**Comment by b4rt3kpl** [comment]
Hi Maxim,

Can I add this myself?

In which file is such code?

 

BR, Bartek

**Comment by AuthenticEshkinKot** [comment]
Of course, you can try to add it, but you'll have to change more than one file. This is how I see the changes:

1. main.php: we need to get the list of projects from Mantis API and add them to page in hidden tag
2. status_grid.js/devs_grid.js: add dropdown list to page and fill it with project names, add callbacks for the dropdown which update current page

**Comment by b4rt3kpl** [comment]
OK, I think it is more complicated as I thought ;-(

 

Do you plan do this in short future?

**Comment by AuthenticEshkinKot** [comment]
I think I'll do it till the end of next week.

**Comment by b4rt3kpl** [comment]
Thank You!

 

Are You on LinkedIn?

**Comment by AuthenticEshkinKot** [comment]
Yes, I have LinkedIn account.
If you talk about statuses, then first of all you need to add your custom status to Mantisbt - https://www.mantisbt.org/manual/admin.customize.status.html
After that you should add your status to Taskodrome using its configuration page - Manage -> Manage Plugins -> Taskodrome.
If you mean users, then you should add user to Mantisbt - it will appear in Taskodrome.

**Comment by b4rt3kpl** [comment]
Hi Maxim,

I have alerady added statuses and users, but I write about adding project name and status in this place:

**Comment by AuthenticEshkinKot** [comment]
In what place?
Now there is no way to distinguish issues by project, but I will add it.

**Comment by AuthenticEshkinKot** [comment]
Unfortunately, I see only empty string. I suppose, you posted image or something else.

**Comment by b4rt3kpl** [comment]
OK,

This same picture in attached file.

 

BR, Bartek

**Comment by AuthenticEshkinKot** [comment]
@b4rt3kpl
Unfortunately, there is no any attachment here (on github) or in email notification. If you want to show me the image, please, feel free to send it to maxriderg@gmail.com or to post it here, but not via email response on github's notification (because it doesn't work in such a way).

**Comment by AuthenticEshkinKot** [comment]
@b4rt3kpl 
I've checked everything once again and found, that Taskodrome shows tasks from one particular project, currently chosen in Mantis. Dropdown list with projects can be found in right upper corner.
Example for Mantis-1.2:
![mantis_1 2_projects](https://cloud.githubusercontent.com/assets/2103955/22865360/cd2cbb72-f17b-11e6-86d7-15c181df5ffa.jpeg)
